`timescale 1ns/1ps

// 仅用于独立综合 SOURCE_Q28=1 分支；完整 Block 顶层直接参数化 runtime_quantizer_ctrl。
module runtime_quantizer_q28_top #(
    parameter integer CTRL_ADDR_WIDTH = 28
)(
    input  wire                         clk,
    input  wire                         rst_n,
    input  wire                         ddr_init_done,
    input  wire                         start,
    input  wire [12:0]                  cfg_vector_length,
    input  wire [12:0]                  cfg_rows,
    input  wire [6:0]                   cfg_groups,
    input  wire [CTRL_ADDR_WIDTH-1:0]   cfg_source_addr,
    input  wire [CTRL_ADDR_WIDTH-1:0]   cfg_activation_addr,
    input  wire [CTRL_ADDR_WIDTH-1:0]   cfg_raw_scale_addr,
    input  wire [CTRL_ADDR_WIDTH-1:0]   cfg_combined_scale_addr,
    output wire [CTRL_ADDR_WIDTH-1:0]   axi_awaddr,
    output wire                         axi_awuser_ap,
    output wire [3:0]                   axi_awuser_id,
    output wire [3:0]                   axi_awlen,
    input  wire                         axi_awready,
    output wire                         axi_awvalid,
    output wire [255:0]                 axi_wdata,
    output wire [31:0]                  axi_wstrb,
    input  wire                         axi_wready,
    output wire [CTRL_ADDR_WIDTH-1:0]   axi_araddr,
    output wire                         axi_aruser_ap,
    output wire [3:0]                   axi_aruser_id,
    output wire [3:0]                   axi_arlen,
    input  wire                         axi_arready,
    output wire                         axi_arvalid,
    input  wire [255:0]                 axi_rdata,
    input  wire                         axi_rvalid,
    output wire                         busy,
    output wire                         done,
    output wire                         error,
    output wire [7:0]                   error_code,
    output wire [31:0]                  saturated_count,
    output wire                         all_zero,
    output wire [15:0]                  max_abs_q10,
    output wire [23:0]                  max_mantissa_binary32,
    output wire signed [9:0]            max_exponent_binary32,
    output wire [31:0]                  max_abs_binary32_bits,
    output wire [3:0]                   debug_state
);

runtime_quantizer_ctrl #(
    .SOURCE_Q28(1),
    .CTRL_ADDR_WIDTH(CTRL_ADDR_WIDTH)
) u_runtime_quantizer_ctrl (
    .clk                     (clk),
    .rst_n                   (rst_n),
    .ddr_init_done           (ddr_init_done),
    .start                   (start),
    .cfg_vector_length       (cfg_vector_length),
    .cfg_rows                (cfg_rows),
    .cfg_groups              (cfg_groups),
    .cfg_source_addr         (cfg_source_addr),
    .cfg_activation_addr     (cfg_activation_addr),
    .cfg_raw_scale_addr      (cfg_raw_scale_addr),
    .cfg_combined_scale_addr (cfg_combined_scale_addr),
    .axi_awaddr              (axi_awaddr),
    .axi_awuser_ap           (axi_awuser_ap),
    .axi_awuser_id           (axi_awuser_id),
    .axi_awlen               (axi_awlen),
    .axi_awready             (axi_awready),
    .axi_awvalid             (axi_awvalid),
    .axi_wdata               (axi_wdata),
    .axi_wstrb               (axi_wstrb),
    .axi_wready              (axi_wready),
    .axi_araddr              (axi_araddr),
    .axi_aruser_ap           (axi_aruser_ap),
    .axi_aruser_id           (axi_aruser_id),
    .axi_arlen               (axi_arlen),
    .axi_arready             (axi_arready),
    .axi_arvalid             (axi_arvalid),
    .axi_rdata               (axi_rdata),
    .axi_rvalid              (axi_rvalid),
    .busy                    (busy),
    .done                    (done),
    .error                   (error),
    .error_code              (error_code),
    .saturated_count         (saturated_count),
    .all_zero                (all_zero),
    .max_abs_q10             (max_abs_q10),
    .max_mantissa_binary32   (max_mantissa_binary32),
    .max_exponent_binary32   (max_exponent_binary32),
    .max_abs_binary32_bits   (max_abs_binary32_bits),
    .debug_state             (debug_state)
);

endmodule
